apiVersion: v1
kind: Service
metadata:
  name: minio-lb
spec:
  type: LoadBalancer
  ports:
    - name: minio-app-port
      protocol: TCP
      port: 5002
      targetPort: 5002
  selector:
    name: minio
    instance: minio-prj